variables:
  BUNDLE_PATH: $(Pipeline.Workspace)/.bundle

trigger: none

# schedules:
# - cron: "0 0 * * *"
#   displayName: Daily midnight build
#   branches:
#     include:
#     - develop

pool:
  vmImage: 'macOS-10.15'

name: $(Date:yyyyMMdd)$(Rev:rr)
steps:
  - template: common/setup.yml

  # Test + Azure reports

  - bash: bundle exec fastlane test ui:true --env test
    displayName: fastlane run tests

  - template: common/publish_reports.yml
