variables:
  - group: Fastlane-Env
  - name: BUNDLE_PATH
    value: $(Pipeline.Workspace)/.bundle

pr:
  - master
  - develop

trigger: none

pool:
  vmImage: 'macOS-10.15'

name: $(Date:yyyyMMdd)$(Rev:rr)
steps:
  - template: common/setup.yml

  # Test + Azure reports

  - bash: bundle exec fastlane test --env test
    displayName: fastlane run tests

  - template: common/publish_reports.yml
