variables:
  - group: Fastlane-Env
  - group: Fastlane-Env-Enterprise
  - name: BUNDLE_PATH
    value: $(Pipeline.Workspace)/.bundle

pr: none

trigger: none

pool:
  vmImage: 'macOS-10.15'

name: $(Date:yyyyMMdd)$(Rev:rr)
steps:
  - template: common/setup.yml

  # Install all required provisiong profiles

  - task: InstallAppleProvisioningProfile@1
    inputs:
      provProfileSecureFile: 'Ebolapp_Enterprise.mobileprovision'

  - task: InstallAppleProvisioningProfile@1
    inputs:
      provProfileSecureFile: 'Ebolapp_Widget_Enterprise.mobileprovision'

  # Install all required certificates

  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: 'enterprise_dist_cert.p12'
      certPwd: '$(enterprise_cert_pw)'
      keychain: 'temp'

  # Test + Azure reports

  - bash: bundle exec fastlane test --env test
    displayName: fastlane run tests

  - template: common/publish_reports.yml

  # Install badge (imagemagick)
  
  - bash: brew bundle
    displayName: brew bundle

  # Remove framework
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        rm -R Ebolapp/Resources/Frameworks/Common/CommonCode.framework

  # Build and upload

  - bash: bundle exec fastlane build_and_deploy build_number:$(Build.BuildNumber) --env enterprise
    displayName: fastlane build&deploy

